---
- name: test
  hosts: localhost
  become: yes
  become_user: root
  roles:
    - kbrebanov.docker
    - tersmitten.composer
  tasks:
    - name: stop nginx
      service: name=nginx state=stopped

